### ISSUE TITLE
Missing screenshot in appdata file

### ISSUE THREAD

**Issue by City-busz** [transmission-remote-gtk/transmission-remote-gtk#101]
The specified screenshot is missing here:
https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/master/data/io.github.TransmissionRemoteGtk.appdata.xml.in#L27

Try to open, and you'll get `403 - Forbidden: Access is denied.`:
http://eth0.org.uk/~alan/transmission-remote-gtk-1.1.1.png

**Comment by ajf8** [comment]
Thanks, this is fixed now
