### ISSUE TITLE
Additional dependencies to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by JohanAR** [transmission-remote-gtk/transmission-remote-gtk#105]
I had to install the following packages to be able to build on Ubuntu 20.04:

* libjson-glib-dev
* appstream-util

The latter was a bit tricky because autogen.sh told me that appstream-glib was missing (despite being installed ofc.)

**Comment by TingPing** [comment]
I've never been a fan of keeping the list of dependencies in the readme, its always wrong.

I added a wiki page for this: https://github.com/transmission-remote-gtk/transmission-remote-gtk/wiki/Build-dependencies

However I think @ajf8 needs to enable user editing of wiki pages.

**Comment by JohanAR** [comment]
ok, just wanted to raise awareness in case you wanted to update it :)
