### ISSUE TITLE
--minimized switch not working

### ISSUE THREAD

**Issue by c-janousek** [transmission-remote-gtk/transmission-remote-gtk#11]
When invoked with the --minimized switch the client does not start in a minimized state. Looks similar to the issue with the comprehensive Transmission client documented at 
https://trac.transmissionbt.com/ticket/4605

**Comment by LaserEyess** [comment]
It doesn't work for me unless I have these options ticked in local preferences 

![](https://0x0.st/sm8o.png)

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967
