### ISSUE TITLE
Feature request: select multiple torrents with the Shift key

### ISSUE THREAD

**Issue by areographe** [transmission-remote-gtk/transmission-remote-gtk#115]
Hi, really appreciate this utility for managing my RPi Transmission Daemon. One request is the ability to select multiple torrents in the main list using <kbd>Shift</kbd> and the arrow keys. Currently, using <kbd>Ctrl</kbd> and arrow keys, plus <kbd>Space</kbd> to select, works fine, but it would be useful to be able to select a swathe of torrents when the list is sorted by tracker etc.

**Comment by philzin** [comment]
It's odd that it doesn't work for you; I can already do this. Maybe there is an issue on your end?

**Comment by areographe** [comment]
Could well be, is there anything you can suggest I do to find the cause of the issue? I ran `transmission-remote-gtk` from a terminal in case any visible errors appeared when I try to use <kbd>Shift</kbd><kbd>↓</kbd> but nothing came up.

**Comment by hadess** [comment]
> It's odd that it doesn't work for you; I can already do this. Maybe there is an issue on your end?

I don't see how it can work, Shift+Up and Shift+Down are both used as accelerators for changing the priority of a torrent:
```
    priv->mb_up_queue = trg_menu_bar_item_new(GTK_MENU_SHELL(torrentMenu),
                                              _("Move Up Queue"),
                                              FALSE);
    trg_menu_bar_accel_add(menu, priv->mb_up_queue, GDK_Up,
                           GDK_SHIFT_MASK);

    priv->mb_down_queue =
        trg_menu_bar_item_new(GTK_MENU_SHELL(torrentMenu),
                              _("Move Down Queue"),
                              FALSE);
    trg_menu_bar_accel_add(menu, priv->mb_down_queue, GDK_Down,
                           GDK_SHIFT_MASK);
```

The accelerators should be removed or changed.

**Comment by LaserEyess** [comment]
fd745b70266b336b6970ddf3505f3d231b9c28d1
