### ISSUE TITLE
1.4.0 app-id change causes disassociation on gnome dock

### ISSUE THREAD

**Issue by miigotu** [transmission-remote-gtk/transmission-remote-gtk#116]
Since the .desktop file has been renamed to `io.github.TransmissionRemoteGtk.desktop` and no longer matches the name of the executable, you cannot right click the icon of the running executable on the dock and add to favorites, and if you add it in the overview and then start nit you end up with 2 icons in the dock, one of which you can click to add to favorites and one which you cannot.

Renaming the desktop file to `transmission-remote-gtk.desktop` fixes the issue and the launcher and dock work as expected. This is because the running application `transmission-gtk` has no matching desktop file, so there is no information about it.

Images to show before renaming the desktop file and after renaming it, both with the app open and with it closed.
![transmission-remote gtk](https://user-images.githubusercontent.com/390379/106403105-e03d0000-63fa-11eb-8243-77256b8c68fe.png)

**Comment by TingPing** [comment]
Was fixed by https://github.com/transmission-remote-gtk/transmission-remote-gtk/commit/2c91f0f76752811fbde98186400ae8c224000e6a
