### ISSUE TITLE
Time for a version bump?

### ISSUE THREAD

**Issue by iskarian** [transmission-remote-gtk/transmission-remote-gtk#122]
It has been two and a half years since the last release, and downstreams are [now](https://src.fedoraproject.org/rpms/transmission-remote-gtk/tree/rawhide) [carrying](https://git.benjamin.barenblat.name/debian-transmission-remote-gtk/tree/debian/patches/) [patches](https://packages.gentoo.org/packages/net-p2p/transmission-remote-gtk/changelog), particularly for the [GCC-10 fix](https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/92). Perhaps it's time to bump the version?

**Comment by ajf8** [comment]
Hi there, yes I was just thinking we should do one! There's some key patches and this is overdue. What do you think @TingPing?  I can bump the version, run autoconf, and publish an archive here on github is there anything else you think needs doing?

**Comment by ajf8** [comment]
Thanks Patrick, your help is much appreciated. 1.4.2 is now released, over 10 years since the first :)
