### ISSUE TITLE
Don't resize the 'Name' column when opening client

### ISSUE THREAD

**Issue by NSQY** [transmission-remote-gtk/transmission-remote-gtk#148]
When using 'Classic style' the 'Name' column is expanded (to make room for torrents with exceptionally long names?). I would prefer if this did not happen. The action happens over the course of about a second, rather than being instant. I think this is because the entire torrent list is still being updated. If I'm being particularly impatient, I will instinctively grab at it multiple times. Annoying.

**Comment by LaserEyess** [comment]
Duplicate of #22. Not sure how to fix it.

**Comment by NSQY** [comment]
Closing this then.
