### ISSUE TITLE
Feature request: Automatically add .torrent files from directory

### ISSUE THREAD

**Issue by Kteby** [transmission-remote-gtk/transmission-remote-gtk#15]
There is a very handy feature is standalone transmission client called "Automatically add .torrent files from directory" in Downloading section of Preferences. 

Lack of this feature and inability to minimize application to tray by clicking exit button (Fedora 23, Gnome 3.18.2) are what stops me from using it all the time instead of original transmission client.

**Comment by oppa1** [comment]
You can do that.

Take a look at **watch-dir** and **watch-dir-enabled** in https://trac.transmissionbt.com/wiki/EditConfigFiles

**Comment by TingPing** [comment]
@oppa1 local vs remote though.

**Comment by Kteby** [comment]
I've just added 

  "watch-dir": "/home/blukpun/Downloads", 
  "watch-dir-enabled": true

to the end of /home/blukpun/.config/transmission-remote-gtk/config.json file and it changed nothing.

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967

(Also this seems out of scope)
