### ISSUE TITLE
Add @LaserEyess to project

### ISSUE THREAD

**Issue by TingPing** [transmission-remote-gtk/transmission-remote-gtk#157]
Hey @ajf8 what do you think about adding @LaserEyess to the project. They've been doing great work lately and it would probably be helpful for them to be able to triage bugs and such.

**Comment by LaserEyess** [comment]
The only reason I haven't asked so far is that I feel like my C skills (let alone gtk skills) aren't quite up to snuff to be given unconditional merge access. That being said, for smaller things I (probably) won't break anything.

I would like to help triage/close issues though.

**Comment by TingPing** [comment]
I'll still spend some time on review but I believe you'll continue to improve.

A release sounds like a decent idea.

**Comment by LaserEyess** [comment]
I guess *I* can close this now. About the release, I want to try to finish the labels PR first, though I'm dragging my feet with it because I keep trying to fix `trg-state-selector.c` first.

**Comment by ajf8** [comment]
Honestly I've only just seen this issue today after I invited @LaserEyess to be a maintainer a few days ago :) But thank you for suggesting this in case I didn't notice, I would have done so if I saw this issue before. I check github infrequently but saw the recent activity and was really impressed.
