### ISSUE TITLE
Invisible text of dropdowns in transmission-remote-gtk

### ISSUE THREAD

**Issue by simonbcn** [transmission-remote-gtk/transmission-remote-gtk#16]
Arch Linux 64 bits
transmission-remote-gtk git version (compiled/installed today)
Gnome Shell

When I add a torrent, it opens a window with the info of torrent, etc. but the texts in dropdown of "_Destination folder_" and "_Apply to all_" are unreadable:

[![Screencast](http://img.youtube.com/vi/cbM6KCCt9OE/0.jpg)](https://www.youtube.com/watch?v=cbM6KCCt9OE)

**Comment by TingPing** [comment]
Regarding "Apply to all" I don't think there is any bug there, it is just using a poor widget for the job, the drop down decides what to do out of a few actions and does not have any thing that should be shown.

**Comment by simonbcn** [comment]
Ok, that commit is in master branch? What branch I have to download to test this commit?

**Comment by TingPing** [comment]
@simonbcn For future reference the PR says at the top the branch name "TingPing:destination-combo"
so you would just use `git checkout destination-combo` from my repo.
