### ISSUE TITLE
Open Torrent Folder

### ISSUE THREAD

**Issue by username227** [transmission-remote-gtk/transmission-remote-gtk#161]
Hi, is there any way to set up the program to open the remote path to the torrent? This is an important feature that I'm sure many would like to have. Thanks.

**Comment by LaserEyess** [comment]
There is, see https://github.com/transmission-remote-gtk/transmission-remote-gtk/wiki/Local-Command-usage. I don't think adding any other functionality to do this is a good idea. This program is for remotely managing a transmission-daemon instance, it is not a library organization tool or a remote file manager and it shouldn't strive to be. If you need something like that take a look at [Sonarr ](https://sonarr.tv/ )and the like, they have support for transmission's RPC.

**Comment by LaserEyess** [comment]
There have been a few other issues like this. I maintain that trg is not a file manager and shouldn't strive to be.
