### ISSUE TITLE
Use clipboard contents as default for add magnet link dialog

### ISSUE THREAD

**Issue by dannywoodz** [transmission-remote-gtk/transmission-remote-gtk#167]
Using the current clipboard text content as a default for the value in the 'Add torrent from URL' would be a nice workflow improvement.  I find it pretty common to have copied the magnet link from somewhere before bringing that dialog up, so having it pre-populated is another action that doesn't have to be taken.

What do you think?  I have a simple implementation (diffable here: https://github.com/transmission-remote-gtk/transmission-remote-gtk/compare/master...dannywoodz:torrent-add-clipboard-default?expand=1) that I've been using for a few weeks, and it works pretty well.  Happy to raise as a PR if you'd like.

**Comment by TingPing** [comment]
I think it sounds pretty reasonable.

You should ignore all clipboard content that isn't clearly a URI though.

**Comment by dannywoodz** [comment]
Yeah, was thinking of that, but the code ended up messier than I liked for a small change, and I wanted to scope out appetite for it first.  Easy with g_uri_is_valid, but I see in the README that glib is potentially 2.56, and the useful URI functions didn't appear until 2.66.

If all we're checking for is http(s) or magnet prefixes then it's easy to perform a lightweight check, which I'm happy to update my fork with.  Do you think that would be enough?

**Comment by dannywoodz** [comment]
Updated the linked code with a very lightweight check for http, https, or magnet.

**Comment by TingPing** [comment]
I was going to just suggest `g_str_has_prefix()` honestly but yeah, that looks good.

**Comment by TingPing** [comment]
A small concern of mine is that you should check if the entry already has text. `gtk_clipboard_request_text()` is async and could complete after a user starts typing, in theory at least.

**Comment by dannywoodz** [comment]
Fair point, but difficult one to test.  I've updated the code with a simple empty-string comparison that should work in that case.

**Comment by dannywoodz** [comment]
Since we're talking at this level of detail, I've raised a pull request at https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/168.

**Comment by LaserEyess** [comment]
I think #168 covered this
