### ISSUE TITLE
Spacing all broken in recent git versions

### ISSUE THREAD

**Issue by hadess** [transmission-remote-gtk/transmission-remote-gtk#178]
I'm guessing e274990256638ed6ebda8dba3af832c07ec56736 is the culprit.

Git:

![git-version](https://user-images.githubusercontent.com/769861/159490948-1c2f65eb-f6ad-452f-a067-ec5252eee79d.png)

1.4.2:

![1.4.2](https://user-images.githubusercontent.com/769861/159490950-d229b247-d762-4db2-8857-6d7b05c1a947.png)

**Comment by LaserEyess** [comment]
Yes that was a noted side-effect of the refactor, but unfortunately the functionality does not exist to recreate how it looked before. I agree this should be fixed but it requires some thought on my part.

**Comment by hadess** [comment]
> Yes that was a noted side-effect of the refactor, but unfortunately the functionality does not exist to recreate how it looked before. I agree this should be fixed but it requires some thought on my part.

Just set `valign` to "START` not `FILL` on all the children (or unset `row-homogeneous` on the container).

![image](https://user-images.githubusercontent.com/769861/176547705-64ac7f10-9c20-4b8c-a711-fd4dfb07ae8b.png)
