### ISSUE TITLE
icons broken after adwaita-icon-theme upgrade

### ISSUE THREAD

**Issue by ilf** [transmission-remote-gtk/transmission-remote-gtk#179]
After upgrading [adwaita-icon-theme](https://gitlab.gnome.org/GNOME/adwaita-icon-theme) from [41.0](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/tags/41.0) to [42.0](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/tags/42.0), many icons in 1.4.2 are broken:

![transmission-remote-gtk](https://user-images.githubusercontent.com/160771/162159460-f13dcd48-4d27-4639-877d-8ec09bcc8ad8.png)

**Comment by LaserEyess** [comment]
Most likely fixed by https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/136, can you try git master?

**Comment by ilf** [comment]
@LaserEyess: Yes, git [current](https://datatracker.ietf.org/doc/html/draft-knodel-terminology) works, thanks!
I thought I saw something on this before and I did search, but I didn't immediately find that.
What do you think about a new release with that included? I think many users would benefit to avoid this issue.

**Comment by LaserEyess** [comment]
A new release is probably needed, yeah. I wanted to try and get labels support in before doing a release but I haven't really had the time to contribute like I did a few months ago. But new features are less important than bug fixes.

**Comment by ilf** [comment]
Release early, release often. :)

**Comment by LaserEyess** [comment]
1.5.0 has been released
