### ISSUE TITLE
How can I extract the messages to translate?

### ISSUE THREAD

**Issue by simonbcn** [transmission-remote-gtk/transmission-remote-gtk#18]
I want to extract all literals from sources files to translate them, how can I extract them?
Thanks.

**Comment by TingPing** [comment]
It is a standard gettext project, all the translations are in the po directory and any common translation tools will work: https://github.com/transmission-remote-gtk/transmission-remote-gtk/tree/master/po

**Comment by simonbcn** [comment]
I have extracted all literals with `xgettext -C -kC -k_ -o es_ES.po src/*.c` but there are some errors with `ngettext` strings. The source code is
```
...
ngettext
("Downloading from %1$"G_GUINT64_FORMAT" of %2$"G_GUINT64_FORMAT" connected peer",
"Downloading from %1$"G_GUINT64_FORMAT" of %2$"G_GUINT64_FORMAT" connected peers"
....
```
But `xgettext`  imports only the first part of string:
```
...
#: src/torrent-cell-renderer.c:329
msgid "Downloading from %1$"
msgid_plural "Downloading from %1$"
msgstr[0] ""
msgstr[1] ""
....
```

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967
