### ISSUE TITLE
Why not link to Flatpak/Downloads in the README? 

### ISSUE THREAD

**Issue by Pentaphon** [transmission-remote-gtk/transmission-remote-gtk#183]
What the title says. 

https://flathub.org/apps/details/io.github.TransmissionRemoteGtk

**Comment by LaserEyess** [comment]
That flatpak is not part of this project. I don't know who makes it, but if they want to come here and ask to have it added or even add support to this repo for building a flatpak they'd be more than welcome.

**Comment by hfiguiere** [comment]
I remember pinging @TingPing back then.

**Comment by LaserEyess** [comment]
@hfiguiere I'm slightly unfamiliar with how flathub works, but is it possible to build a flatpak out of this repo? Or does it need to be a separate repo that flathub reads from.

**Comment by hfiguiere** [comment]
you need a manifest. The one on flathub is a good start, but need tailoring for use with a source tree.

Now if you want to add it to github actions, there is this option:

https://github.com/marketplace/actions/flatpak-builder

**Comment by LaserEyess** [comment]
Ok, I'll look into adding it. If it's something we can deploy ourselves it might be a good idea.

**Comment by Pentaphon** [comment]
@hfiguiere thanks for contacting @LaserEyess , I hope you guys work together to integrate the existing Flatpak into the original project, as this project is sorely in need of a way to distribute it to all Linux distros that users will see has the endorsement and involvement of the original authors.

**Comment by hfiguiere** [comment]
The thing is that way flathub work is that the flatpak manifest is in a separate repository. There is currently no streamlined options to do otherwise (it's a case by case)

If you want access to it to do updates, let me know, I'll ask an admin. (hi @TingPing )

**Comment by LaserEyess** [comment]
Well for now, since I know where the flatpak is coming from, I think adding it to the README is fine. But I mean, I don't think distros will care that we advertise a flatpak, most of them are likely doing their own packaging. It might be a good idea to list the distros that package this project in the readme too.

**Comment by Pentaphon** [comment]
> I think adding it to the README is fine

Yeah, that's pretty much all I was hoping for at the very least. Your users definitely need at least one official way to download it from the README and as long as you add a Flatpak link/button to the README, that will show that users that the original author is ok with his project being on Flathub. @hfiguiere seems to be enthusiastic about updating it so he will probably just keep doing it for you, with your knowledge and approval.

**Comment by TingPing** [comment]
> It might be a good idea to list the distros that package this project in the readme too.

My opinionated take is to bless the Flatpak as the recommended installation. It will always be up to date, run everywhere, and we do have access to fix issues with it (Sorry @LaserEyess wasn't too aware of it but indeed I was).

Listing distro packages is mostly unhelpful and often just points people to outdated and unsupported software. Ubuntu 20.04 will likely never get newer than 1.4.1.
