### ISSUE TITLE
[Feature] Limit of active downloads

### ISSUE THREAD

**Issue by guglovich** [transmission-remote-gtk/transmission-remote-gtk#195]
Please make a limit of active downloads, instead of just limiting downloads as now. At the moment the download limit is very often useless, because there are downloads with 0 peers and only wastes the limit, while there are distributions with peers. Or this setting just doesn't work correctly.

**Comment by TingPing** [comment]
I believe transmission only exposes `download-queue-size` and has no way of distinguishing a limit for only active downloads.

**Comment by LaserEyess** [comment]
First, this project does not control RPC, that's [transmission](https://github.com/transmission/transmission). We only consume RPC as a client. Second, you're looking for `queue-stalled-enabled` and `queue-stalled-minutes`, see [here](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#41-session-arguments). If these don't work for you then you'll have to make a feature request on transmission's issue tracker.
