### ISSUE TITLE
Add country flags to Host, Country or IP column in Peers tab

### ISSUE THREAD

**Issue by penguinpee** [transmission-remote-gtk/transmission-remote-gtk#197]
First of all, thank you for an excellent remote gui client for Transmission. I only recently switched from [transgui](https://github.com/transmission-remote-gui/transgui), which hasn't been updated in a long time, but kept working through every system upgrade. So, I kind of had no need to look for something else.

One thing I grew fond of is the little country flag displayed in front of the IP/Host (depending on name resolution being enabled). It allows for a quick scan of the country of origin.
![transgui_flags](https://user-images.githubusercontent.com/98259694/187068118-bee59b1c-c934-4876-9b25-488191f1982f.png)

It would be nice to have that functionality available in this client.

**Comment by LaserEyess** [comment]
#119

**Comment by penguinpee** [comment]
I overlooked that one. Thanks for the pointer.
