### ISSUE TITLE
Request: Trash downloaded data instead of deleting them

### ISSUE THREAD

**Issue by xiota** [transmission-remote-gtk/transmission-remote-gtk#199]
Since adding an option to hide file deletion to prevent accidental deletion is unacceptable (#198), I am requesting that a Trash feature be added.  Since computers can be "halfway around the world", they may not be guaranteed to have active trash system.  So transmission-remote-gtk would have to manage the temporary holding space itself.  Such a system should track whether torrents have simply been removed or removed with deletion.

**Comment by LaserEyess** [comment]
This is impossible to implement in `transmission-remote-gtk`. There is no access to the remote filesystem provided for transmission's RPC. If you want this feature, you must first add it to RPC.

**Comment by xiota** [comment]
> This is impossible to implement in transmission-remote-gtk.

Transmission could just track locally what is pending removal without actually removing remotely until the "Trash" is "emptied".

**Comment by LaserEyess** [comment]
If you want this feature implemented you need to ask here: https://github.com/transmission/transmission
