### ISSUE TITLE
Minimize to tray option not working

### ISSUE THREAD

**Issue by penguinpee** [transmission-remote-gtk/transmission-remote-gtk#213]
This issue might have been around for a while (see #39), but today I noticed and I felt it's a nice to have. I have the relevant option enabled:

![transmission-remote-minimize-system-tray](https://user-images.githubusercontent.com/98259694/207288666-74bc2bae-ec44-404a-8977-2ac7e04180f4.png)

**Bonus points:** _minimize_ is the correct AE spelling, whereas _minimise_ is the correct BE spelling. Not sure what the standard is.

Since the implementation of the tray icon is currently debated (see #192), please consider this bug low priority. The GTK4 port (see #117) is more important. But should the tray icon return/survive, I would very much like to see this option working.

**Comment by LaserEyess** [comment]
I guess I shouldn't have closed the other one, whoops. To be honest, I'm leaning much more on the side of "just remove the tray", sorry. But this sort of seems independent of tray functionality.

**Comment by LaserEyess** [comment]
This option is now gone
