### ISSUE TITLE
TControlInvalidatePreferredSize loop detected error

### ISSUE THREAD

**Issue by winbatch** [transmission-remote-gtk/transmission-remote-gtk#215]
Seem to be receiving this quite frequently..  Windows 11, version 5.0.2
<img width="266" alt="image" src="https://user-images.githubusercontent.com/2419795/209166361-cd842b65-979c-41f3-a4e2-4bd0d76fdf6d.png">

**Comment by LaserEyess** [comment]
You're going to need to provide more information on this, in particular:

- How did you build trg?
- What are the reproduction steps?
- Do you have any other logs about this?

**Comment by winbatch** [comment]
- I didn't build it - I downloaded it.  Likely from here: https://sourceforge.net/projects/transgui/
- I think just clicking on it in the pinned task bar to maximize it
- Not sure where logs are stored but happy to provide them if you can point me to them.

**Comment by LaserEyess** [comment]
https://github.com/transmission-remote-gui/transgui

**Comment by winbatch** [comment]
ah, no worries, didn't realize I got it from the wrong place.  Updated to 5.18.0.  Fingers crossed!
