### ISSUE TITLE
`View → Statistics`  crashes the app a few seconds later

### ISSUE THREAD

**Issue by ai** [transmission-remote-gtk/transmission-remote-gtk#217]
I have Transmission Remote GTK from Flathub.

I use it to connect to Transmission 3.0/4.0 daemon on my home server in local network.

The app crashes a few time per day.

Unfortunately, I didn’t find any pattern to reproduce the error. The console log is clean and GNOME Problem Reporting has no data:

```
2023-02-09-16:15:09> Error: No segments found in coredump './coredump'
2023-02-09-16:15:09* ('report_uReport' salió con 1)
```

I use Fedora 37. How I can collect some data to help finding the crashes reason?

**Comment by TingPing** [comment]
```
flatpak install flathub io.github.TransmissionRemoteGtk.Debug org.gnome.Sdk//42
flatpak run --devel --command=gdb io.github.TransmissionRemoteGtk transmission-remote-gtk
```

Type `r` then enter. Wait for a crash.

Run `bt full` after the crash. Paste results here.

**Comment by ai** [comment]
Now it’s freezes after I am going to `View → Statistics`

```
Thread 1 "transmission-re" received signal SIGSEGV, Segmentation fault.
0x000055555558b264 in trg_update_stats_timerfunc (data=0x555555d04560) at ../src/trg-stats-dialog.c:256
256	    if (TRG_IS_STATS_DIALOG(data)) {
zsh: suspended (tty output)  flatpak run --devel --command=gdb io.github.TransmissionRemoteGtk
```

It closes debug session, so I can’t enter `bt full`.

**Comment by ai** [comment]
I found a way to reproduce it (at least on my machine):

1. Open View → Statistics.
2. Wait for a few seconds.

With debugger, it will freeze. Without debugger, it will crash.

**Comment by LaserEyess** [comment]
I can't reproduce this on master, and I'm not too familiar with how to debug flatpaks, any chance you can try this on master?

**Comment by LaserEyess** [comment]
If you can still reproduce this in 1.6.0, please re-open this. But the interface with the daemon was completely re-written and should be more robust now.

**Comment by ai** [comment]
I will check on 1.6 release to Flathub https://flathub.org/ru/apps/io.github.TransmissionRemoteGtk

**Comment by mskiptr** [comment]
> If you can still reproduce this in 1.6.0, please re-open this. But the interface with the daemon was completely re-written and should be more robust now.

Hmm, I've been seeing some silent crashes for a while now and today I decided to finally investigate. The symptoms look very much like what's described in this bug report, but **they are** present on `1.6.0`.

I can reliably trigger and observe the segfault by spinning up an environment with GDB and Transmission Remote GTK 1.6.0 in it, connecting to the daemon, opening the stats popup and then closing it.

```sh
guix shell gdb transmission-remote-gtk -- \
    gdb -ex run \
        --args sh -c 'exec transmission-remote-gtk'
```

If I do the same but ask the package manager to compile version `1.7.0` for me, the crashes go away:

```sh
guix shell gdb transmission-remote-gtk --with-version=transmission-remote-gtk=1.7.0 -- \
    gdb -ex run \
        --args sh -c 'exec transmission-remote-gtk'
```

Now, I would normally think this was simply fixed somewhere between those two versions – most likely in #251. But then why would it _also_ go away in the Flatpak build of 1.6.0 (way before that PR)?

FWIW, I doubt that compiling 1.7.0 vs using binary substitutes for 1.6.0 makes a difference. I did verify that the package builds deterministically (tho I did not try recompiling all of its dependencies).

**Comment by mskiptr** [comment]
Well, I guess segfaults are inherently unpredictable to some extent. And they can absolutely depend on how the compiler (or even malloc) organizes the memory layout. So it isn't surprising for the crashes to only occur with specific builds.
