### ISSUE TITLE
xdotool: XGetWindowProperty[_NET_WM_DESKTOP] failed

### ISSUE THREAD

**Issue by sebastian-65** [transmission-remote-gtk/transmission-remote-gtk#219]
**Expected behaviour (worked on transmission-gtk 3.00)**

window=$(xdotool search --desktop 0 --name "Transmission" | tail -n 1) # get transmission window ID
xdotool windowunmap $window # hiding the application
xdotool windowactivate $window # unhide the application

**Current behaviour**

After transmission-gtk upgrade from 3.00 to 4.0.1-2:

xdotool windowunmap $window # hiding works
xdotool windowactivate $window # unhide returns an error:

`XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)`

----

Did something change that might have caused this issue?

**Comment by LaserEyess** [comment]
Wrong project: https://github.com/transmission/transmission/issues

**Comment by sebastian-65** [comment]
I'm sorry @LaserEyess, feel free to close this down. Thank you!

Migrated issue can be found here: https://github.com/transmission/transmission/issues/5158
