### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pferor** [transmission-remote-gtk/transmission-remote-gtk#223]
Hello.
I'm not sure if this is the right place for this, but I'll do it here anyway.

In order to have a better environment options, there should be two options to choose from:

  * Minimize to tray: thanks, it's already there. "Close" closes the program, and "Minimize" goes to tray.
  * Close to tray: Minimize normally, but close to tray. And to close, right click on the tray icon and choose "Close".

Thanks.

**Comment by LaserEyess** [comment]
#205
