### ISSUE TITLE
TRG craches on resuming large number of torrents.

### ISSUE THREAD

**Issue by van-de-bugger** [transmission-remote-gtk/transmission-remote-gtk#225]
transmission-remote-gtk-1.5.1-3.fc38.x86_64

How to reproduce:

1. Start TRG.
2. In the left pane click on "All".
3. Then activate the right pane and press `Ctrl`+`A` to select all torrents.
4. Pause the selected torrents.
5. When all the torrents are shown as paused, click on "Paused" in the left pane.
6. Resume them.

Result: TRG crashes.

TRG prints to the console:

    (transmission-remote-gtk:134236): Json-CRITICAL **: 02:32:40.530: json_node_get_node_type: assertion 'JSON_NODE_IS_VALID (node)' failed
    (transmission-remote-gtk:134236): Json-CRITICAL **: 02:32:40.530: json_array_get_int_element: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_VALUE' failed
    (transmission-remote-gtk:134236): Json-CRITICAL **: 02:32:40.530: json_node_get_node_type: assertion 'JSON_NODE_IS_VALID (node)' failed
    (transmission-remote-gtk:134236): Json-CRITICAL **: 02:32:40.530: json_array_get_int_element: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_VALUE' failed
    Segmentation fault (core dumped)

Note 1: The "resume" command is completed successfully. If TRG is restarted, all the torrents are resumed, no torrents are in paused state.

Note 2: It does not matter how to pause and resume torrents. It can be made through the menu, context menu, by clicking buttons on the toolbar, or by pressing `Ctrl`+`P` and `Ctrl`+`R`, but **step 5 is critical** in order to reproduce crash. If step 5 is skipped, TRG does **not** crash.

Note 3: In my case, the crash is reproducible with 610 torrents.

**Update:**

I am experimenting with number of torrents. I still have 610 torrent total, but on the step 3 I select not all but just a few torrents, 3 or 5. In such a case TRG behaves a bit differently: instead of immediate crash, it stops responding. GNOME shows dialog: "Transmission Remote is not responding" with two buttons "Force quit" and "Wait". It seems TRG runs infinite loop, since it consumes 25% of CPU on my 4-core system. I have to click "Wait" many times, and only then TRG crashes with only one message "Segmentation fault (core dumped)" in the console.

**Comment by LaserEyess** [comment]
I cannot reproduce this. I did it with 3000 torrents and it worked fine. I suspect I fixed quite a few bugs with the curl threadpool by implementing #196. Maybe it's time for a new release.

**Comment by LaserEyess** [comment]
If you can still reproduce this in 1.6.0, please re-open this. But the interface with the daemon was completely re-written and should be more robust now.

**Comment by van-de-bugger** [comment]
The problem is reproducible with TRG 1.6.0:

```
$ ./transmission-remote-gtk
(transmission-remote-gtk:552663): Json-CRITICAL **: 01:18:44.609: json_node_get_node_type: assertion 'JSON_NODE_IS_VALID (node)' failed
(transmission-remote-gtk:552663): Json-CRITICAL **: 01:18:44.609: json_array_get_int_element: assertion 'JSON_NODE_TYPE (node) == JSON_NODE_VALUE' failed
Segmentation fault (core dumped)
```

Stack back trace of the first two threads (seems other threads do not matter for this GTK assertion failure):

```
(gdb) i thr
  Id   Target Id                          Frame 
* 1    Thread 0x7fe6827fc6c0 (LWP 553412) 0x00007fe698cc8339 in json_array_get_int_element () from /lib64/libjson-glib-1.0.so.0
  2    Thread 0x7fe696ef3a80 (LWP 552663) 0x00007fe698d22450 in g_str_hash () from /lib64/libglib-2.0.so.0
  3    Thread 0x7fe6897ff6c0 (LWP 552664) 0x00007fe698a29b5d in syscall () from /lib64/libc.so.6
  4    Thread 0x7fe688ffe6c0 (LWP 552665) 0x00007fe698a2435d in poll () from /lib64/libc.so.6
  5    Thread 0x7fe683fff6c0 (LWP 552666) 0x00007fe698a2435d in poll () from /lib64/libc.so.6
  6    Thread 0x7fe6811fe6c0 (LWP 552678) 0x00007fe698a2435d in poll () from /lib64/libc.so.6
(gdb) i s
#0  0x00007fe698cc8339 in json_array_get_int_element () at /lib64/libjson-glib-1.0.so.0
#1  0x0000562b43d91db8 in trg_file_parser_node_insert (priorities=0x562b49559590, enabled=0x562b45006010, index=257, file=0x562b45f82360, last=<optimized out>, top=<optimized out>)
    at ../src/trg-files-model.c:222
#2  trg_files_model_buildtree_threadfunc (data=0x562b44c84c10) at ../src/trg-files-model.c:370
#3  0x00007fe698d6f893 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#4  0x00007fe6989ab907 in start_thread () at /lib64/libc.so.6
#5  0x00007fe698a31870 in clone3 () at /lib64/libc.so.6
(gdb) thr 2
[Switching to thread 2 (Thread 0x7fe696ef3a80 (LWP 552663))]
#0  0x00007fe698d22450 in g_str_hash () from /lib64/libglib-2.0.so.0
(gdb) i s
#0  0x00007fe698d22450 in g_str_hash () at /lib64/libglib-2.0.so.0
#1  0x00007fe698d230dc in g_hash_table_lookup () at /lib64/libglib-2.0.so.0
#2  0x00007fe698ccbf03 in json_object_get_int_member () at /lib64/libjson-glib-1.0.so.0
#3  0x0000562b43d893ac in torrent_get_id (t=<optimized out>) at ../src/torrent.c:66
#4  0x0000562b43daa2ac in trg_torrent_model_update (model=0x562b44988320, tc=tc@entry=0x562b448f3910, response=<optimized out>, mode=mode@entry=3) at ../src/trg-torrent-model.c:629
#5  0x0000562b43d96c20 in on_torrent_get (data=0x562b44c7c560, mode=3) at ../src/trg-main-window.c:1077
#6  0x0000562b43d8f6a8 in rpc_callback (source=<optimized out>, result=<optimized out>, user_data=0x562b449c0260) at ../src/trg-client.c:641
#7  0x00007fe698ee009c in g_task_return_now () at /lib64/libgio-2.0.so.0
#8  0x00007fe698ee3e03 in g_task_return () at /lib64/libgio-2.0.so.0
#9  0x00007fe698c8c084 in send_and_read_splice_ready_cb () at /lib64/libsoup-3.0.so.0
#10 0x00007fe698ee009c in g_task_return_now () at /lib64/libgio-2.0.so.0
#11 0x00007fe698ee3e03 in g_task_return () at /lib64/libgio-2.0.so.0
#12 0x00007fe698c89141 in send_and_splice_ready_cb () at /lib64/libsoup-3.0.so.0
#13 0x00007fe698ee009c in g_task_return_now () at /lib64/libgio-2.0.so.0
#14 0x00007fe698ee3e03 in g_task_return () at /lib64/libgio-2.0.so.0
#15 0x00007fe698ebe333 in async_ready_splice_callback_wrapper () at /lib64/libgio-2.0.so.0
#16 0x00007fe698ee009c in g_task_return_now () at /lib64/libgio-2.0.so.0
#17 0x00007fe698ee3e03 in g_task_return () at /lib64/libgio-2.0.so.0
#18 0x00007fe698ec3dcd in real_splice_async_complete_cb () at /lib64/libgio-2.0.so.0
#19 0x00007fe698ee009c in g_task_return_now () at /lib64/libgio-2.0.so.0
#20 0x00007fe698ee3e03 in g_task_return () at /lib64/libgio-2.0.so.0
#21 0x00007fe698ebf4fd in async_ready_close_callback_wrapper () at /lib64/libgio-2.0.so.0
#22 0x00007fe698ee009c in g_task_return_now () at /lib64/libgio-2.0.so.0
#23 0x00007fe698ee00d5 in complete_in_idle_cb () at /lib64/libgio-2.0.so.0
#24 0x00007fe698d3d39d in g_idle_dispatch () at /lib64/libglib-2.0.so.0
#25 0x00007fe698d4139c in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00007fe698d9f438 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#27 0x00007fe698d3ea23 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00007fe698f15ffd in g_application_run () at /lib64/libgio-2.0.so.0
#29 0x0000562b43d86855 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.c:62
```
