### ISSUE TITLE
Tracker URL edit issue

### ISSUE THREAD

**Issue by drws** [transmission-remote-gtk/transmission-remote-gtk#230]
There is an issue with editing trackers' list in the _Trackers_ tab in detailed view below. A tracker's URL cannot be changed when the base URL stays the same. For example, an URL `http://tracker.tld` cannot be changed into `http://tracker.tld?pass=1337`. An _error setting announce list_ message is shown instead.

**Comment by LaserEyess** [comment]
Please split issues into individual tickets, also the first one is a transmission daemon bug, please report that upstream.

**Comment by drws** [comment]
This has been [reported](https://github.com/transmission/transmission/issues/5802) upstream.
