### ISSUE TITLE
Message: no method name

### ISSUE THREAD

**Issue by mcdemon05** [transmission-remote-gtk/transmission-remote-gtk#236]
When connecting to transmission for the first time, the message "no method name" appears
Next time you connect everything is ok.
Then if you disconnect and connect, the message does not appear.

But if you exit the application and start it again, the first connection will fail again with the message "no method name"

how fix it?

**Comment by LaserEyess** [comment]
You need to give more information. Can you add the `TRG_CLIENT_DEBUG` env and paste the RPC calls that create that error? You can censor any torrent data if you wish.

**Comment by mcdemon05** [comment]
sorry but I newbie in Linux
I should add env via export command?
but I show all env in my linux and see that all env's have "=" and somthing else (like `GJS_DEBUG_TOPICS=JS ERROR;JS LOG`)

Maybe after TRG_CLIENT_DEBUG need add somthing else?

**Comment by LaserEyess** [comment]
```sh
TRG_CLIENT_DEBUG=1 transmission-remote-gtk > log.txt 2>&1
```

This will print everything to log.txt

**Comment by mcdemon05** [comment]
[log.txt](https://github.com/transmission-remote-gtk/transmission-remote-gtk/files/12286116/log.txt)

**Comment by LaserEyess** [comment]
Something seems wrong here, are you editing out `X-Transmission-Session-Id` header? Because otherwise this doesn't look right. What is your daemon/web server set up like?

**Comment by LaserEyess** [comment]
@mcdemon05 ping on this. I am inclined to think this is an issue with how you set up your daemon

**Comment by mcdemon05** [comment]
Daemon inludes in router and configured by router vendor (Keenetic).
Router vendor sayed that it's problem transmission client....
I just started using another transmission remote client (tremotesf) and no more suffer by this problem.
