### ISSUE TITLE
Overestimated seeder and leecher count?

### ISSUE THREAD

**Issue by drws** [transmission-remote-gtk/transmission-remote-gtk#239]
Seeder and leecher counts seem to count their occurrence in _every_ tracker of the torrent, meaning that some are counted multiple times, leading to overestimated numbers. Only unique ones should be counted.

**Comment by stefantalpalaru** [comment]
Fixed in "master": https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/224
