### ISSUE TITLE
Finished torrent

### ISSUE THREAD

**Issue by joshuamabina** [transmission-remote-gtk/transmission-remote-gtk#241]
At what point is a torrent marked as finished?

**Comment by LaserEyess** [comment]
A torrent is marked as finished if RPC returns [`isFinished` from a `torrent-get`](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#33-torrent-accessor-torrent-get).

From[ the docs](https://github.com/transmission/transmission/blob/main/libtransmission/transmission.h#L1599-L1601): 
```cpp
    /** A torrent is considered finished if it has met its seed ratio.
        As a result, only paused torrents can be finished. */
```
