### ISSUE TITLE
About relationship between launchpad translations and upstream translations

### ISSUE THREAD

**Issue by hosiet** [transmission-remote-gtk/transmission-remote-gtk#28]
[Launchpad.net](https://translations.launchpad.net/transmission-remote-gtk/) is providing translation platform for transmission-remote-gtk. My question is whether these translations will feed back to upstream, or do I need to make a pull request here as well? If it will, how often will you merge launchpad translations?

Thanks.

**Comment by ajf8** [comment]
Hey! It used to be (on google code) a manual process where I would update all of the translations periodically, or if someone let me know they had worked on a translation, but this doesn't really happen anymore.

I think pull requests are the best way forward. If you submit one I'll be happy to merge it! Thanks :+1:
