### ISSUE TITLE
Annoyance: transmission does not become top focus window after clicking on magnet link

### ISSUE THREAD

**Issue by markcroft1975** [transmission-remote-gtk/transmission-remote-gtk#30]
HI

would be nice to make transmission become focus after selecting the magnet link off a website at the moment i click on link and then need to move down and make tranmission the focus window on top of google chrome. i am running linux mint 17.3 64bit.
transmission v2.82 (14160)

(sorry got bad english cos of dyslexia)

**Comment by zeroedout** [comment]
Hrmm, I'm not getting this on Arch Linux with version 1.3.1 on Chrome Version 53.0.2785.92 (64-bit) and GNOME 3.20.2. To test this I did:
1. Went to https://www.archlinux.org/download/ and clicked the first magnet link for the September 3rd ISO (magnet:?xt=urn:btih:657c483dc66c1f248fc2eda5f5682ea557233e7a&dn=archlinux-2016.09.03-dual.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce). 
2. Chrome opened an external protocol dialogue asking me to launch an application (the xdg default for magnets). 
3. Transmission Remote GTK opens up with the Add Torrent dialogue. I can click open to make the torrent start.

My first guess, if you're running older versions of something, maybe try upgrading?

**Comment by TingPing** [comment]
I also cannot reproduce with latest version.

**Comment by vicente-reyes** [comment]
I don't know if it's the same exact cause, but this happens to me.
Running Gnome on Arch 64 bit with transmission-gtk 2.92-5 and google-chrome 56.0.2924.87-1
When transmission is not running, it will open and become top focus after opening a magnet. The problem happens when clicking a link while it is already running.
It happens with Firefox too

**Comment by markcroft1975** [comment]
it how vicente-reyes describes it sorry , i was not clear enough. The first it works fine for the first torrent but everyone after that it still sits in the background and not request where to download the files... i will make a video if that helps better then my dyselixa english...

**Comment by alexberry** [comment]
I can confirm this issue too. Fedora 25, Chrome 57, Transmission 2.92. If transmission is closed, then upon clicking the magnet link, it gains focus after opening. If clicking a magnet link once transmission is open then transmission does not get focus.

**Comment by gkaklas** [comment]
Hey guys

This issue tracker/repository is for transmission-remote-gtk, a GTK client that controls a transmission-daemon. I noticed that you are referring to "Transmission 2.92" and "v2.82", which seems like you are referring to a different project, the official [Transmission GTK client](https://github.com/transmission/transmission). If you still have these issues you should probably open an issue there. 😉

**Comment by vicente-reyes** [comment]
Now I feel dumb
Thanks
