### ISSUE TITLE
When clicking on a torrent the progress bar appears full

### ISSUE THREAD

**Issue by cjdg** [transmission-remote-gtk/transmission-remote-gtk#33]
Every time i click into a torrent, the selected torrent progress bar appears full

**Comment by gkaklas** [comment]
I cannot reproduce this on v1.3.1, do you still have this issue?

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967
