### ISSUE TITLE
appstream-util validate gives style errors on transmission-remote-gtk.appdata.xml

### ISSUE THREAD

**Issue by bbarenblat** [transmission-remote-gtk/transmission-remote-gtk#37]
appstream-util 0.6.4 refuses to validate transmission-remote-gtk.appdata.xml on style grounds:

> transmission-remote-gtk.appdata.xml:FAILED:
> ? style-invalid         : Content before <ul> is too short [122], at least 300 characters required

This should be pretty easy to fix by changing the description from bullet points to prose.

**Comment by ajf8** [comment]
The appstream file now validates with --pedantic on the latest debian. Thanks for the report and sorry for the delay fixing it.
