### ISSUE TITLE
Migrating issues from code.google.com

### ISSUE THREAD

**Issue by andreygursky** [transmission-remote-gtk/transmission-remote-gtk#4]
Hi Alan,

I've seen already a couple of projects migrated from code.google.com. The issues have been also auto(?) migrated. Other projects are still available in read-only mode on code.google.com, but for transmission-remote-gtk I will be auto-redirected to github. The www.archive.org tells that somewhere since August..October the redirection is enforced making issues to be lost. Hopefully you can fix this?

P.S. Do you still maintain this project? You could add a new release on github to inform GNU/Linux distribution maintainers, that there is a 1.2 version. At least Debian seems to be not aware of this.

Regards,
Andrey

**Comment by ajf8** [comment]
Hi Andrey,

Yeah, I got the redirect setup but thought I could still get the issues out, it seems I can't though. I go to the export tool and it says "this project has already been migrated".

A lot of those issues are outdated, lets just recreate any that are important I guess, sorry I didn't export it. Anyone please copy issues from archive.org into github if they are still causing problems.

As for me maintaining the project... Obviously I have not been very active on it, but I am committed to keeping it working, and I do still use it occasionally. It's 5 years old now and I have a lot less time to maintain it than when most of the work was done on it. Contributions are especially welcome (I usually test and merge these fairly quickly) and I would consider adding people as developers on the project if they do good work. :+1: 

I'll look into creating releases on github, and try to look at some of the issues sometime.

**Comment by andreygursky** [comment]
> I go to the export tool and it says "this project has already been migrated".

Maybe you could get in touch with Google support by google-code-shutdown@google.com? It seems one should additionally rename the repository on Github [1]. It would be great still to have
the full history of the project at the place where it is maintained. By the way, have you tried this [2]? Perhaps you can access the issues with this tool and upload them, though renaming is unavoidable, since the new issues started from 1.

The archive.org didn't dump the whole project, but Google created a new site for it [3]. I'm wondering, why not to preserve code.google.com in read-only mode and treat it as the archive instead of creating yet another "archive" with not accessible full revision history (or I'm missing something?).

> but I am committed to keeping it working

It's good to know, since I noticed a fragmentation process have started: [4], [5], [6]. So for now we have already at least 4 independent transmission-remote-gtk projects (including your original one). Some fixes can be found in [7]. And some people somehow succeeded to have all the issues [5], [8]. It means it was possible to migrate the project multiple times... Curious but nice feature.

[1] https://code.google.com/p/support-tools/wiki/GitHubExporterFAQ#Error_%22Project_already_exists.%22
[2] https://code.google.com/p/support-tools/wiki/IssueExporterTool
[3] https://code.google.com/archive/p/transmission-remote-gtk
[4] https://github.com/TingPing/transmission-remote-gtk
[5] https://github.com/Treferwynd/transmission-remote-gtk
[6] https://github.com/DriverXX/transmission-remote-gtk
[7] https://github.com/EnigmaCurry/transmission-remote-gtk
[8] https://github.com/simonbcn/transmission-remote-gtk

**Comment by ajf8** [comment]
Sure, I'll have another go at exporting and send them a mail if I can't export.

Wow, didn't know there was that much work in other forks. A lot of it seems quite recent, in the last few weeks.

The work by @TingPing looks really great, it's good to see cleanup on the build system and GTK deprecations. I would love to see that merged. Please could you send a PR @TingPing? :)

@DriverXX - your code changes look good too, and translation updates are always welcome, please could you also send them in a PR?

**Comment by andreygursky** [comment]
@robol, you made also a couple of minor fixes (I spotted firstly by EnigmaCurry), maybe they are worth a PR?

**Comment by TingPing** [comment]
> The work by @TingPing looks really great, it's good to see cleanup on the build system and GTK deprecations. I would love to see that merged. Please could you send a PR @TingPing? :)

My plans are quite intrusive but I'm not sure I'll ever get that far.

**Comment by TingPing** [comment]
On a related note do  you have any IRC channel? Can be much better than issues for some conversations.

**Comment by ajf8** [comment]
There is #transmission-remote-gtk on freenode, which I see you have found. I've joined and will be around occasionally.

**Comment by LaserEyess** [comment]
I'm gonna close some older issues that are before ~2020 ish because a lot has changed in trg and, while some of them seem valid, a lot of them are hard to confirm. If a particular issue is still bothering you, please open a new one.

For example, this one does not seem relevant. A lot has changed since this project was on github.
