### ISSUE TITLE
Changes to the ‘automatically connect’ checkbox in local preferences don't persist

### ISSUE THREAD

**Issue by rhendric** [transmission-remote-gtk/transmission-remote-gtk#43]
I can only change the setting by editing config.json. 🙁

**Comment by alcarraz** [comment]
Same here, no setting are being stored to the setting files and therefore are being ignored, in my case the setting changes don't even apply to the current running instance

**Comment by gkaklas** [comment]
Which version are you running, is it the latest? I'm running 1.3.1 and I don't have this issue 🤔

**Comment by ajf8** [comment]
Same, I tried to reproduce and could not.

**Comment by rhendric** [comment]
Just checked again and it seems to have been fixed for me too! :tada:

**Comment by mgedmin** [comment]
I have the same problem with the *Options dialog on add* setting:
1. Open local preferences
2. Switch to General tab
3. Uncheck Options dialog on add
4. Hit OK

Repeat steps 1 and 2 and you'll see the option is still checked.

I'm using transmission-remote-gtk 1.3.1-2 from Ubuntu 17.04.
