### ISSUE TITLE
Smarter search

### ISSUE THREAD

**Issue by Elinvention** [transmission-remote-gtk/transmission-remote-gtk#46]
Currently, if I want to download a torrent with many files(~2000) and I want to look for a specific file, I press `crtl+f`, so I can look up the file by name, but I have to enter the exact name from the beginning. 

For example if all files begin with a sequential number, it can't find any file unless I specify that number, making the search functionality useless.

If someone could point me to the relevant part of the source code I may try to make a pull request.

**Comment by ajf8** [comment]
I guess this search equals function needs to be set on the tree view in question.

https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-set-search-equal-func

**Comment by ajf8** [comment]
https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/master/src/trg-files-tree-view.c#L203

**Comment by ajf8** [comment]
Thanks 👍
