### ISSUE TITLE
[adding torrent] Cannot edit folder to save

### ISSUE THREAD

**Issue by andreygursky** [transmission-remote-gtk/transmission-remote-gtk#5]
After migration to Gtk3 you can't anymore enter a new location, since the widget is not editable. It would be even better to have an editable widget to choose from a recently used list and a button to choose the location with FileChooser.

**Comment by ajf8** [comment]
Thanks for the report, I think this is 270 from the google code issue tracker.

This was definitely working with GTK3, I removed GTK2 support quite a while back (IIRC), and as so little has changed (especially in that code) I suspect a regression or change in behaviour in GTK3.

Will try to have a look sometime.

**Comment by ajf8** [comment]
A FileChooser would be great... I seem to remember looking at this but it's very geared towards the local filesystem, and the daemon is remote. The client doesn't know much about the layout of the remote filesystem anyway, just where your torrents are and the paths saved in config.

**Comment by andreygursky** [comment]
> I think this is 270 from the google code issue tracker.

Yes, a workaround patch has been proposed there by a user, which e-mail address I could not decrypt even being logged in on my google account. By the way, maybe you could disable the automatic redirection until things with migrating issues become clearer?

> This was definitely working with GTK3

I've been sticked for a long time with a manually compiled GTK2 version (with some backports), thus I haven't noticed that it used to work previously with GTK3. And I still think about maintaining a Gtk2 version, since among other issues a Gtk3 version must be started on command line with GTK_OVERLAY_SCROLLING=0 due to these new fancy scroll bars which appear "if needed" and... hide the infos you're actually want to view!

> and the daemon is remote

Yes, I've realised this also, that the daemon should send the remote folder list. But this would be a great security hole, so better to live with manual addition.

**Comment by ajf8** [comment]
You are not the first person who has mentioned using GTK2 still, if it's something people want then I would be happy to see support added back in.

I kept support for both for quite some time (until way after debian moved to GTK3, which was one of the last distros), and GTK3 support seemed to be working well (to me at least), so I removed the GTK2 support. Then a bunch of regressions came :(

Yeah, scrolling got messed up over time. Not sure if it's the same issue, but it used to work nicely with the resizable columns but that got broken and I had to make the columns autosize instead. I tracked it down to a commit and reported it to the GTK devs, and they reverted it. But of course it takes a long time for everyone to get this fix in their distro.

**Comment by TingPing** [comment]
> You are not the first person who has mentioned using GTK2 still, if it's something people want then I would be happy to see support added back in.

My opinion is that is a rather short-sighted move. Every day Gtk3 moves further and further from Gtk2 so you either end up with effectively two frontends or you end up with a bad Gtk3 app.

**Comment by ajf8** [comment]
OK, maybe I don't remember very well the pain of maintaining both versions :)

**Comment by kanyck** [comment]
Please bring GTK2 support back! The pain is supporting GTK3 versions, gtk2 usually just works)))
transmission-remote-gtk is one of very few apps that pull gtk3 into my system and I'll be happy to get rid of it at all!

**Comment by TingPing** [comment]
Fixed by b6bb8fb323f3885e106c0606de050c0437ccf81f

**Comment by andreygursky** [comment]
I've been using and improving the mentioned patch. Thanks for redesign, but the issue I'm trying to fix in that patch is now here upstream after redesign: the last used path is not auto selected on next time a dialog is opened.

**Comment by TingPing** [comment]
> the issue I'm trying to fix in that patch is now here upstream after redesign: the last used path is not auto selected on next time a dialog is opened.

Seems to work perfectly for me, do you have any specific steps to reproduce?

I specifically set the last selection in this snippet (It will even now warn if it fails): https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/b6bb8fb323f3885e106c0606de050c0437ccf81f/src/trg-destination-combo.c#L330-L338

**Comment by andreygursky** [comment]
Now I caught it. The first time one enters a new path, it will not be saved in last_selection. Once one selects this the next time from the combobox it will be saved in last_selection and appears as expected. Thus it would be better 1) to save it already for the very first time it has been added and 2) not to issue a warning if the path doesn't exist anymore (e. g., there are no torrents anymore with such destination folder and it's OK) but select a previously used one. However this would be too complicated, then just leave it empty as is now.

**Comment by TingPing** [comment]
Ah that makes sense, wouldn't be too hard to fix 1 probably, but storing multiple previous destinations seems unnecessary.

**Comment by LaserEyess** [comment]
I think this should be mostly fixed? Please open a new issue if it isn't.

See also: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967
