### ISSUE TITLE
Properties dialog not showing all tabs when using Classic Style view

### ISSUE THREAD

**Issue by gkaklas** [transmission-remote-gtk/transmission-remote-gtk#50]
However, the dialog shows all tabs when using one of the other styles. Is this intentional? Probably "Classic Style" assumes that you also have the "Torrent Details" section visible, but that may not always be the case.

**Comment by gkaklas** [comment]
I wasn't sure if this was the (only) purpose of `TrgTorrentPropsDialogPrivate.show_details`, but now I figured that this behaviour is intentional. But why is only the "Limits" tab displayed? If the user really wants to use the "Torrent Details" window I guess that he would like to see the "Limits" tab there too. 🤔 (and if he doesn't they would probably want to see every info in the properties window)

What do you think? If you agree, can I make a PR to remove this check for the properties window and try to add the "Limits" tab on the "Torrent Details" view?

**Comment by ajf8** [comment]
It's a good idea which I never thought about :)

Please go ahead, would be happy to test and merge it.

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967

More than willing to look at a PR to implement the feature you want.
