### ISSUE TITLE
"%{path}" local variable doesn't work

### ISSUE THREAD

**Issue by MasterGroosha** [transmission-remote-gtk/transmission-remote-gtk#51]
Hi there! On Kubuntu 16.04 and the latest transmission-remote-gui, `%{path}` variable doesn't work (even though [Wiki](https://github.com/transmission-remote-gtk/transmission-remote-gtk/wiki/Local-Command-usage) mentions it.
`%{name}` and `%{full-path}` work fine, however `%{path}` doesn't :(

**Comment by ajf8** [comment]
Thanks for pointing this out, I fixed the page. I just checked the RPC spec and think you might want %{downloadDir}
