### ISSUE TITLE
General download/upload speed cannot be set in preferences

### ISSUE THREAD

**Issue by ffries** [transmission-remote-gtk/transmission-remote-gtk#56]
In remote preferences, download and upload speed cannot be set in the GUI. I need to connect with remote console, stop daemon, change values and restart.

Kind regards,,

**Comment by kanyck** [comment]
The same on my system. Noticed that the server icon is now hidden unless the mouse is over it. The dialog window opens and seems okay but speeds don't change. Some other settings don't change, too, like peer-limit-per-torrent, some do, like alternative speed on/off.

**Comment by LaserEyess** [comment]
Not sure if this is the same issue, but editing this value in TRG does nothing for me, and setting it to anything just has it revert to whatever it is in settings.json after I reload the remote preferences menu: 

![img](https://i.imgur.com/WEnZ76U.png)

However toggling it DOES work, and I can change the value in the webui, this value is updated correcting in TRG. So it is parsing the value correctly and sending the RPC command to toggle global upload limits, but it is not setting global upload limit correctly.

**Comment by LaserEyess** [comment]
On closer inspection, it seems like nothing with a "spin wheel" is working? I tried cache size, port, and every setting in limits in remote preferences. The "spin wheel" implementation seems to be broken and I don't know how or why.

**Comment by LaserEyess** [comment]
@TingPing This is definitely fixed in https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/66, and can be closed.
