### ISSUE TITLE
[adding torrent] Text in "Destination folder" and "Apply to all" not visible

### ISSUE THREAD

**Issue by andreygursky** [transmission-remote-gtk/transmission-remote-gtk#6]
See subject.
Sometimes after choosing a folder for the second time it becomes visible.

**Comment by TingPing** [comment]
Fixed by b6bb8fb323f3885e106c0606de050c0437ccf81f

**Comment by andreygursky** [comment]
It's still not visible in "Apply to all" for me.

**Comment by TingPing** [comment]
Apply to all isn't supposed to show anything, its a drop down of possible actions and contains no 'selection'.

**Comment by andreygursky** [comment]
You're right. It looks ambiguously though. Do you know any such combobox'es for analogously purposes in other gtk guis?

**Comment by TingPing** [comment]
No, personally I would just show the top-level directory in the file list and toggling the cells on that would effectively be "apply to all" and just remove that combobox entirely.

**Comment by andreygursky** [comment]
Or in general and that is I believe how one suppose such things to work. Select what you want (ctrl-a for all), then just click on only one arbitrary checkbox to switch download/skip for the whole selection. And click on priority field to switch normal/high/low also for all selected items.

**Comment by TingPing** [comment]
I've never seen cells work with selections like that, nor do I think that is clear, typically selection deals with right click menus, action bars, or dnd.

**Comment by andreygursky** [comment]
Aha, the right-click menu is already here, that's good, but somehow I hadn't thought about it in first place.

For example, a firefox extension flashgot: choose "flashgot all", then you can select items and by clicking for yes/no for one of them, it gets applied for all selected, which I find as expected. And there is also a selection filter, which would be nice thing here.
