### ISSUE TITLE
feature request: close to tray

### ISSUE THREAD

**Issue by tidux** [transmission-remote-gtk/transmission-remote-gtk#69]
An extra option to close to tray as well as minimize to tray, disabled by default, would be nice.  Many other programs such as Cantata already do this.

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967

I'm not quite sure how this is different than minimize to tray, too.

**Comment by oliverlew** [comment]
while, it's a special case, but in most tiling window managers, there is no minimize for windows.

And, systray is normally used in occasions where the main window is not opened. Minimizing a window should be just a trick of WMs to not showing the window. So I think close to systray is still useful.

**Comment by LaserEyess** [comment]
I use sway and I can "close" to tray just fine. I'm guessing here the difference is when you click the close button (x) vs the minimize button (_), you want the same behavior?

**Comment by tidux** [comment]
What do you mean you guess?  Sway was not your firsr computer UI so you know exactly what the difference is between minimize and close.

**Comment by LaserEyess** [comment]
Technically? I understand the difference. Practically? On Windows the difference would be if the icon is in the task bar or not. What does it do for you on GNOME/KDE that it doesn't already? No icon in the dock? No offense but this project isn't swimming with developers, this small change in functionality does not seem like it would be very worth my time. 

I am not against it, but you'd have to give me a better reason than "other programs do this".

**Comment by oliverlew** [comment]
Actually, despite technical details (which I am not an expert at), transmission-remote-gtk is not the kind of application that needs to stay in the background. We just connect to the daemon whenever we need, and closing it does not lose anything.

> this small change in functionality does not seem like it would be very worth my time

So if it's easy to implement, you can consider keeping it in the todo list (or wait for a PR); otherwise, I personally am not against keeping this issue closed.
