### ISSUE TITLE
Download bandwidth not respected

### ISSUE THREAD

**Issue by jdtanner** [transmission-remote-gtk/transmission-remote-gtk#70]
Transmission Remote GTK version 1.3.1
Transmission-daemon version 2.92 (14714)

Expected behaviour: Set download bandwidth in remote dialog to value x, remote transmission then is limited to bandwidth x

Actual behaviour: Set download bandwidth in remote dialog to value x, remote transmission then is limited to bandwidth previously set and not equivalent to x

Setting the bandwidth limited via the web interface to transmission-daemon works as expected.

**Comment by LaserEyess** [comment]
Probably #56

**Comment by LaserEyess** [comment]
@jdtanner did https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/66 fix this for you?

**Comment by TingPing** [comment]
Duplicate of #56
