### ISSUE TITLE
409 error

### ISSUE THREAD

**Issue by ArchangeGabriel** [transmission-remote-gtk/transmission-remote-gtk#75]
Hi,

I get 409 error when trying to connect to my server.

When going to the rpc endpoint in my browser I can see this:
```
409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

    When reading a response, get its X-Transmission-Session-Id header and remember it
    Add the updated header to your outgoing requests
    When you get this 409 error message, resend your request with the updated header

This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: <sometoken>
```

It started recently and wasn’t happening before, but I haven’t found anything related in recent changes on both systems (i.e. server and client).

**Comment by LaserEyess** [comment]
Try to see if https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/76 fixes it

**Comment by ArchangeGabriel** [comment]
Yes it does, thanks a lot! :)

What I don’t get is what it started to happen all of sudden, and especially why it is not happening for someone else accessing the same server (I just noticed today that another user with whom I share the server and for which I know they uses transmission-remote-gtk added some torrents after I opened this ticket —haven’t been in touch with that person yet but that would have been my next step)…

**Comment by LaserEyess** [comment]
So the difference for me was that I had updated nginx. Technically headers are supposed to be parsed case insensitively, according to the spec. I guess nginx wasn't tolower()'ing them or whatever before, but with newer versions it is? 

Interestingly enough, transmission-remote (and possibly transmission-qt) have this exact same bug, they compare headers case-sensitively, so it needs to be fixed there as well.
