### ISSUE TITLE
Allow config.json to be a symlink

### ISSUE THREAD

**Issue by jooola** [transmission-remote-gtk/transmission-remote-gtk#80]
In order to keep my configuration files synced across systems, I use symbolic links to save the configuration in a git repository.

The problem is that transmission-remote-gtk is overwriting the symlink with its own config.json, and I would like to keep this link up to avoid having the manually backup the later.

Is there a way to open the file (and follow the symlink) and write in it instead of simply overwriting the existing file ?

**Comment by ajf8** [comment]
Thanks for the report. Looks like the libglib-json function being used to write the file (json_generator_to_file) uses g_file_set_contents, where this behaviour is documented.

I've made a pull request which fixes it. I'll merge it unless anyone objects.

In the meantime, have you tried symlinking the .config/transmission-remote-gtk directory instead? I think that would work.

**Comment by ajf8** [comment]
Fixed in master, sorry for the delay.
