### ISSUE TITLE
feature request: map drives to local path

### ISSUE THREAD

**Issue by Bureaucromancer** [transmission-remote-gtk/transmission-remote-gtk#81]
Would be really nice to have a feature along the lines of what Transgui for Windows does, allowing a remote path to be mapped to it's local location so we can open the folder something is downloading to, or open a file directly from the gui.

**Comment by OliverLew** [comment]
Hi @Bureaucromancer , I am using a workaround which involves "Local preferences -> actions". See [the WiKi here](https://github.com/transmission-remote-gtk/transmission-remote-gtk/wiki/Local-Command-usage).
For local sessions, I just use 
```
thunar "%{full-path}"
```
And for remote sessions, I use 
```
thunar "sftp://%{username}@%{hostname}%{full-path}"
```
It works quite well. Of course you can use other file managers and sharing methods.

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967

Also it looks like this question has been answered. TRG is not a file manager, you can use local commands to do this, though.
