### ISSUE TITLE
Move away from using stock icons

### ISSUE THREAD

**Issue by eternal-sorrow** [transmission-remote-gtk/transmission-remote-gtk#84]
Stock icons are deprecated in GTK and many custom icon themes do not provide them anymore so TRG ends up using ugly icons from the default system theme.

**Comment by tastytea** [comment]
The [Gtk3 documentation](https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html) recommends using [named icons](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).

**Comment by uzvermode** [comment]
I'm using symbolic toolbar icons, because usually switching light/dark gtk theme



![trg_toolbar_symbolic_icons](https://user-images.githubusercontent.com/1315398/100648562-c2471680-3349-11eb-9d4f-a579ea1c3bef.png)

**Comment by LaserEyess** [comment]
Just FYI I'm working on this as a part of https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/117. Stock icons don't even exist in gtk4, so this is a prerequisite to porting.
