### ISSUE TITLE
Make transmission-remote-gtk respect system gtk theme setting

### ISSUE THREAD

**Issue by kanyck** [transmission-remote-gtk/transmission-remote-gtk#86]
Missing dark theme a lot.. One of few apps that is still an eye-burner...

**Comment by TingPing** [comment]
This is a normal GTK3 application, it does nothing to change theming behavior.

**Comment by kanyck** [comment]
Oh! Indeed, it's gtk3 theming that is broken on my system... again... I still use gtk2 whenever possible that "Just works" for years and have only few gtk3 apps that dropped gtk2 support. Sorry for bothering...
