### ISSUE TITLE
409 Conflict on connect

### ISSUE THREAD

**Issue by kevincianfarini** [transmission-remote-gtk/transmission-remote-gtk#89]
I've just sat my instance on transmission behind an nginx reverse proxy and started getting a 409. Looking through some of the older issues, its seems that this has been an issue in the past. 

When accessing the web, I get on rpc request resulting in a 409 while the others are okay. The response body is as follows:

```
409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

    When reading a response, get its X-Transmission-Session-Id header and remember it
    Add the updated header to your outgoing requests
    When you get this 409 error message, resend your request with the updated header

This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: s2TAaBtDRP5av1kO3okoLoV2YG02jJFq3sD9usahpSGaKhqr
```

Every time I reload the page, I get a single request with a 409 and the rest are okay. transmission remote seems to die on the first request that gives back 409. 

![image](https://user-images.githubusercontent.com/13242326/69600310-1fddb000-0fde-11ea-8e64-5a947f97036d.png)

Any ideas how I could progress?

**Comment by kevincianfarini** [comment]
After looking through the rpc spec for transmission, it appears that we aren't handling CSRF protection correctly. 

[See here](https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt#L56) for how `409 Conflict` to get a session id should be handled.

**Comment by LaserEyess** [comment]
`transmission-remote-gtk` already handles this properly. This is most likely caused by case sensitive headers, see https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/76
