### ISSUE TITLE
No window icon

### ISSUE THREAD

**Issue by hadess** [transmission-remote-gtk/transmission-remote-gtk#96]
The application name in the gnome-shell top bar, and the window icon in the window switcher, don't appear properly since upgrading to transmission-remote-gtk 1.4.1 (probably since 1.4.0 which was the first version to change the application ID).

I tried changing the name of the on-disk icons, but that's not enough:
https://github.com/hadess/transmission-remote-gtk/tree/wip/hadess/fix-icons

(using gnome-shell 3.36 if that makes any difference)

**Comment by Xake** [comment]
fixed by commit 2c91f0f
